#
#Sun Jun 07 12:48:12 COT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--start-maximized, --remote-allow-origins\=*, --disable-notifications, remote-allow-origins\=*], extensions\=[]}
timeouts={implicit\=0, pageLoad\=300000, script\=30000}
